<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'php\\codeformatter\\decorator\\decoratorexception' => '/Decorator/DecoratorException.php',
                'php\\codeformatter\\decorator\\decoratorinterface' => '/Decorator/DecoratorInterface.php',
                'php\\codeformatter\\decorator\\indentation' => '/Decorator/Indentation.php',
                'php\\codeformatter\\decorator\\newlineafter' => '/Decorator/NewLineAfter.php',
                'php\\codeformatter\\decorator\\newlinebefore' => '/Decorator/NewLineBefore.php',
                'php\\codeformatter\\token\\abstracttoken' => '/Token/AbstractToken.php',
                'php\\codeformatter\\token\\deliverer\\builtintokenbuilder' => '/Token/Deliverer/BuiltinToken.php',
                'php\\codeformatter\\token\\deliverer\\delivererinterface' => '/Token/Deliverer/DelivererInterface.php',
                'php\\codeformatter\\token\\deliverer\\selfmadetoken' => '/Token/Deliverer/SelfmadeToken.php',
                'php\\codeformatter\\token\\deliverer\\tokenfactory' => '/Token/Deliverer/TokenFactory.php',
                'php\\codeformatter\\token\\interfacetoken' => '/Token/InterfaceToken.php',
                'php\\codeformatter\\token\\opentag' => '/Token/OpenTag.php',
                'php\\codeformatter\\token\\string' => '/Token/String.php',
                'php\\codeformatter\\token\\tokenizer' => '/Token/Tokenizer.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd